# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20161204_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
