# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20161204_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='stage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
