# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20161206_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='round',
            name='stage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.Stage'),
        ),
    ]
