# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20161224_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
