# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20170113_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_score',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_score',
            field=models.CharField(max_length=30),
        ),
    ]
